services:
  app-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEVEL}
      - POSTGRES_USER=${POSTGRES_USER_DEVEL}
      - POSTGRES_DB=${POSTGRES_DB_DEVEL}
    volumes:
      - ./temp/reports:/usr/src/app/temp/reports
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
  
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 3005:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-backend
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 5428:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEVEL}
      - POSTGRES_USER=${POSTGRES_USER_DEVEL}
      - POSTGRES_DB=${POSTGRES_DB_DEVEL}
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

networks:
  nettrotter:
    external: true