services:
  app-backend:
    build: .
    command: yarn run start:dev
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
      # - ./node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    networks:
      - nettrotter

networks:
  nettrotter:
    external: true